import type { Metadata } from "next";
import { Sora, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";


const sora = Sora({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});

const mono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${sans.variable} ${mono.variable} h-full antialiased`}
    >
      <body className="">
        {children}
      </body>
    </html>
  );
}
